version: '3.7'
services:
  postgres:
    image: postgres
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - postgres
    ports:
      - '8080:80'
    env_file:
      - .env

  twitter-api:
    build:
      context: .
      target: dev
    command: npm run start:dev
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    environment:
      PROD: ${PROD}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSxORD}
      DB_NAME: ${DB_NAME}
    networks:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
